server:
  port: 8080

spring:
  application:
    # O nome que aparecerá no Eureka
    name: ecommerce-api-gateway
  cloud:
    gateway:
      # Propriedades NÃO DEPRECIADAS para o discovery locator
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#      # Rota explícita para o inventory-service (MELHOR PRÁTICA)
#        routes:
#          - id: inventory-service-route
#            uri: lb://inventory-service # O nome do serviço de destino no Eureka
#            predicates:
#              - Path=/inventory-service/**
#            filters:
#              - StripPrefix=1

eureka:
  # A configuração do cliente Eureka com a sintaxe CORRETA
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  # A configuração da instância Eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway